Repository fabric8io/fluent-plugin-kubernetes_metadata_filter, pull requests merged in 2018-05, with the labels that each got.

#128 partial fix to #79. remove json parsing and preserving
  README.md
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: affects/v0.12, affects/v0.14, release/v0.14

#127 bug 1560170. fix error from blocking pipeline if unable to get to api…
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: affects/v0.14, release/v0.12

#132 bug 1560170. fix error from blocking pipeline if unable to get to api…
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: release/v0.14

#130 fix removed feature version
  README.md
Labels: release/v0.14

#131 partial fix to #79. remove json parsing and preserving
  README.md
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: release/v0.12

#112 Implement kubernetes.container_image
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  lib/fluent/plugin/kubernetes_metadata_cache_strategy.rb
  lib/fluent/plugin/kubernetes_metadata_common.rb
  test/cassettes/kubernetes_docker_metadata_using_bearer_token.yml
  test/plugin/test_filter_kubernetes_metadata.rb
  test/plugin/test_watch_pods.rb
Labels: release/v0.14

#135 do not process empty es to avoid stack trace
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: affects/v0.12, affects/v0.14, release/v0.14
