Repository fabric8io/fluent-plugin-kubernetes_metadata_filter, pull requests merged in 2018-04, with the labels that each got.

#118 update to specify proper branches for prs
  README.md
Labels: backport/v0.12, release/v0.14

#119 update to specify proper branches for prs
  README.md
Labels: release/v0.12

#111 FluentD 1.x API and some logging
  circle.yml
  fluent-plugin-kubernetes_metadata_filter.gemspec
  lib/fluent/plugin/filter_kubernetes_metadata.rb
  test/plugin/test_filter_kubernetes_metadata.rb
Labels: release/v0.14
